//------------------------------------------------------------------------------
// <auto-generated>
// 该代码是使用以下工具生成的：
// 运行时版本：4.0.30319.42000
//
// 对文件内容的更改可能会导致不正确的行为，并且在重新生成代码时这些更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingsuCodeEditor.Properties {
    using System;
    
    
    /// <summary>
    /// 用于查找本地化字符串等的强类型资源。
    /// </summary>
    // 该图表是通过 ResGen 或 Visual Studio 等工具从 StronglyTypedResourceBuilder 网格自动生成的类。
    // 要添加或删除成员，请编辑.ResX 文件，
	// 然后使用 /str 选项重新运行 ResGen 或重建 VS 项目构建。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// 返回本示例中使用的缓存的 ResourceManager 模板类实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BingsuCodeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// 此强类型资源类使用当前类的 CurrentUICulture属性进行所有资源查找重写特性线程。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Action {
            get {
                object obj = ResourceManager.GetObject("Action", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Condiction {
            get {
                object obj = ResourceManager.GetObject("Condiction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Const {
            get {
                object obj = ResourceManager.GetObject("Const", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Func {
            get {
                object obj = ResourceManager.GetObject("Func", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Function {
            get {
                object obj = ResourceManager.GetObject("Function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap KeyWord {
            get {
                object obj = ResourceManager.GetObject("KeyWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap nameSpace {
            get {
                object obj = ResourceManager.GetObject("nameSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Setting {
            get {
                object obj = ResourceManager.GetObject("Setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// 查找 System.Drawing.Bitmap类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Variable {
            get {
                object obj = ResourceManager.GetObject("Variable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
